<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Work Request #{{ $workRequest->id }}</title>
  <style>
    body { font-family: Arial, Helvetica, sans-serif; color: #111; }
    .container { width: 800px; margin: 0 auto; }
    .header { text-align: center; margin-bottom: 12px }
    .section { margin-bottom: 10px; }
    .label { font-weight: 700; }
    table { width: 100%; border-collapse: collapse; }
    td, th { padding: 6px; vertical-align: top; }
    .box { border: 1px solid #333; padding: 8px; min-height: 36px }
    .sign { height: 60px; }
    .small { font-size: 12px; }
    .two-cols { display:flex; gap:16px }
    .col { flex:1 }
    .right { text-align:right }
    .dig-badge { font-size:9px; color:#166534; background:#f0fdf4; border:1px solid #86efac; border-radius:3px; padding:2px 6px; margin-top:3px; display:inline-block; }
  </style>
</head>
<body onload="window.print()">
  <div class="container">
    <div class="header">
      <h2>PHILIPPINE SCIENCE HIGH SCHOOL SYSTEM</h2>
      <h3>WORK REQUEST FORM</h3>
    </div>

    <div class="section">
      <table>
        <tr>
          <td style="width:25%" class="label">Issue</td>
          <td class="box">{{ $workRequest->issue ?? '—' }}</td>
        </tr>
        <tr>
          <td class="label">Where</td>
          <td class="box">{{ optional($workRequest->division)->name ?? '—' }} {{ optional($workRequest->office)->name ? ' / ' . optional($workRequest->office)->name : '' }}</td>
        </tr>
        <tr>
          <td class="label">Purpose / Description</td>
          <td class="box">{{ $workRequest->description ?? '—' }}</td>
        </tr>
      </table>
    </div>

    <div class="two-cols section small">
      <div class="col">
        <div><strong>Requested by:</strong></div>
        @if(isset($sigs['submission']['uri']))
          <img src="{{ $sigs['submission']['uri'] }}" alt="requestor signature" style="max-height:48px; display:block; margin:4px auto;" />
        @endif
        <div class="box">{{ optional($workRequest->requester)->name ?? '—' }}</div>
        @if(isset($sigs['submission']))
          <div class="dig-badge">✓ Digitally Signed · {{ optional($sigs['submission']['signed_at'])->format('M d, Y H:i') }}</div>
        @endif
        <div style="margin-top:8px">Signature Over Printed Name</div>
      </div>
      <div class="col">
        <div><strong>Date of Request</strong></div>
        <div class="box">{{ $workRequest->created_at ? $workRequest->created_at->format('F j, Y') : '—' }}</div>
      </div>
      <div class="col">
        <div><strong>Expected Completion Date</strong></div>
        <div class="box">{{ $workRequest->expected_completion_date ? \Carbon\Carbon::parse($workRequest->expected_completion_date)->format('F j, Y') : '—' }}</div>
      </div>
    </div>

    <div class="section">
      <table>
        <tr>
          <td class="label" style="width:30%">Assigned Personnel</td>
          <td class="box">{{ optional($workRequest->assignedUser)->name ?? '—' }}</td>
        </tr>
        <tr>
          <td class="label">Acted By (Completed by)</td>
          <td class="box">{{ optional($workRequest->actedBy)->name ?? '—' }}</td>
        </tr>
        <tr>
          <td class="label">Action Taken</td>
          <td class="box">{{ $workRequest->action_taken ?? '—' }}</td>
        </tr>
        <tr>
          <td class="label">Date Completed</td>
          <td class="box">{{ $workRequest->date_completed ? \Carbon\Carbon::parse($workRequest->date_completed)->format('F j, Y') : '—' }}</td>
        </tr>
      </table>
    </div>

    <div class="two-cols section">
      <div class="col">
        <div class="label">FAD Chief</div>
        @if(isset($sigs['fad_approval']['uri']))
          <img src="{{ $sigs['fad_approval']['uri'] }}" alt="FAD signature" style="max-height:48px; display:block; margin:4px auto;" />
        @endif
        <div class="box sign">&nbsp;</div>
        @if(isset($sigs['fad_approval']))
          <div class="dig-badge">✓ Digitally Signed · {{ $sigs['fad_approval']['name'] }} · {{ optional($sigs['fad_approval']['signed_at'])->format('M d, Y H:i') }}</div>
        @endif
        <div class="small">Signature / Date</div>
      </div>
      <div class="col right">
        <div class="label">Approved</div>
        <div style="margin-top:12px">Status: <strong>{{ $workRequest->status }}</strong></div>
      </div>
    </div>

    <div style="margin-top:18px; font-size:11px; color:#444">Form generated by CRCMIS - {{ now()->toDateTimeString() }}</div>
  </div>

  {{-- Document-level verification QR — mirrors the ITJR PDF footer --}}
  @if(!empty($documentQr))
  <div class="no-print-margin" style="max-width:980px;margin:14px auto 0;border:1px solid #e2e8f0;border-radius:6px;padding:10px 14px;page-break-inside:avoid;">
    <table style="width:100%;border:none;border-collapse:collapse;">
      <tr>
        <td style="border:none;padding:0;width:80px;vertical-align:middle;">
          <img src="data:image/svg+xml;base64,{{ $documentQr }}" style="width:72px;height:72px;display:block;" alt="Verification QR">
        </td>
        <td style="border:none;padding:0 0 0 12px;vertical-align:middle;">
          <div style="font-size:11px;font-weight:bold;color:#1e293b;margin-bottom:2px;">Digitally Signed Document</div>
          <div style="font-size:9.5px;color:#64748b;">{{ count($sigs) }} digital signature(s) on record &mdash; SRMIS, Philippine Science High School System</div>
          <div style="font-size:9px;color:#94a3b8;margin-top:2px;">Scan the QR code to verify all digital signatures and their authenticity</div>
        </td>
      </tr>
    </table>
  </div>
  @endif
</body>
</html>
